### ISSUE TITLE
Players flag when on the edge of ice block

### ISSUE THREAD

**Issue by rimzgg** [alec-jensen/Grumm#1]
### Describe the false positive and how to replicate it

Grim flags when trying to move on the edge of ice, affects all players in my server

https://github.com/alec-jensen/Grumm/assets/92588686/dbfc60f2-d6ce-42d5-9a6f-9fce73def2cb

### Grim version

grimac-2.4.0.jar

### Server version

Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT (Git: c287e92)

### Plugins

BedKillMessages, Brewery, CoreProtect, DiscordSRV, EssentialsX, EssentialsxSpawn, FastAsyncWorldEdit, GrimAC, GSit, LuckPerms, PvPManager, TradeSystem, TreeGravity, WorldGuard

**Comment by alec-jensen** [comment]
2 things. 
1. you are using grim, not grumm
2. you are using an older version of grim

**Comment by alec-jensen** [comment]
This is fixed in the latest version of grim too
